// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package proto.message;

public interface CSLogin1000OrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.message.CSLogin1000)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *账号
   * </pre>
   *
   * <code>string account = 1;</code>
   */
  java.lang.String getAccount();
  /**
   * <pre>
   *账号
   * </pre>
   *
   * <code>string account = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <pre>
   *密码
   * </pre>
   *
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   *密码
   * </pre>
   *
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
