// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package proto.message;

public interface HeartBeat1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.message.HeartBeat1)
    com.google.protobuf.MessageOrBuilder {
}
