// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package proto.message;

public interface SCLogin1001OrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.message.SCLogin1001)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *标识码
   * </pre>
   *
   * <code>int32 status = 1;</code>
   */
  int getStatus();

  /**
   * <pre>
   *错误描述
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *错误描述
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
